version: '3'

tasks:
  publish:
    cmds:
      - pnpm run release:modules
    desc: 'Build and publish versioned packages through Changesets'
    summary: |
      Configure NODE_AUTH_TOKEN before publishing:
        export NODE_AUTH_TOKEN=token
        task publish
